---
- hosts: all
  become: yes

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  tasks:
    - include: tasks/main.yml

    - meta: flush_handlers

    - name: test - check the installed repository
      command: apt-cache policy erlang
      changed_when: false
      register: erlang_test_repo

    - name: test - assert repo URL
      assert:
        that:
          - "'{{ erlang_repo }}' in erlang_test_repo.stdout"

    - name: test - assert that pin is applied
      assert:
        that:
          - "'{{ erlang_pin_priority }} {{ erlang_repo }}' in erlang_test_repo.stdout"

